/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EinsatzForm.java
 *
 * Created on 17.06.2010, 16:24:28
 */

package de.jetb.operator;

import de.jetb.clientutils.Utils;
import de.jetb.connection.PeerManager;
import de.jetb.connection.PeerManager.PresenceListener;
import de.jetb.connection.XMPPRunner;
import java.util.ArrayList;
import javax.swing.AbstractListModel;
import org.jivesoftware.smack.LLPresence;
import org.jivesoftware.smack.XMPPException;

/**
 *
 * @author klocke
 */
public class EinsatzForm extends javax.swing.JFrame {

    private XMPPRunner runner;
    private EinsatzListModel listModel = new EinsatzListModel();
    private PeerManager peerManager;

    /** Creates new form EinsatzForm */
    public EinsatzForm(XMPPRunner runner) {
        this.runner = runner;
        peerManager = runner.getPeerManager();
        peerManager.addPresenceListener(listModel);
        for(LLPresence l : peerManager.getOperatorPresences()){
            listModel.addEinsatzNummer(l.getMsg());
        }
        initComponents();
        einsatznummerField.setText("");
        Utils.centerComponent(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        einsatzListe = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        einsatznummerField = new javax.swing.JTextField();
        cancelButton = new javax.swing.JButton();
        joinButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("jETB");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Laufende Einsätze");

        einsatzListe.setModel(listModel);
        jScrollPane1.setViewportView(einsatzListe);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Neuer Einsatz");

        jLabel3.setText("Einsatznummer");

        einsatznummerField.setText("jTextField1");

        cancelButton.setText("Abbrechen");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        joinButton.setText("Teilnehmen");
        joinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(einsatznummerField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(joinButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(einsatznummerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(joinButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        runner.shutdown();
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void joinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinButtonActionPerformed
        String einsatzNummer = null;
        if(einsatznummerField.getText()!=null &&
                einsatznummerField.getText().trim().length()>0){
            einsatzNummer = einsatznummerField.getText().trim();
        } else {
            einsatzNummer = (String)einsatzListe.getSelectedValue();
        }

        if(einsatzNummer!=null){
            LLPresence myPresence = runner.getService().getLocalPresence();
            myPresence.setMsg(einsatzNummer);
            try {
                runner.getService().updatePresence(myPresence);
                MainWindow window = new MainWindow(runner);
                window.setVisible(true);
                this.setVisible(false);
                this.dispose();
            } catch (XMPPException ex) {
                //TODO: Handle Exception
                ex.printStackTrace();
            }
        } else {
            //TODO: Notify the user that he has to enter a number
        }
    }//GEN-LAST:event_joinButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JList einsatzListe;
    private javax.swing.JTextField einsatznummerField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinButton;
    // End of variables declaration//GEN-END:variables

    private class EinsatzListModel extends AbstractListModel implements PresenceListener{

        private ArrayList<String> einsatzNummern = new ArrayList<String>();

        public void addEinsatzNummer(String nummer){
            if(nummer!=null && !einsatzNummern.contains(nummer)){
                einsatzNummern.add(nummer);
                this.fireContentsChanged(this, 0, einsatzNummern.size());
            }
        }

        public void removeEinsatzNummer(String nummer){
            if(nummer!=null && einsatzNummern.contains(nummer)){
                einsatzNummern.remove(nummer);
                this.fireContentsChanged(this, 0, einsatzNummern.size());
            }
        }

        public int getSize() {
            return einsatzNummern.size();
        }

        public Object getElementAt(int index) {
            return einsatzNummern.get(index);
        }

        public void presenceNew(LLPresence presence) {
            addEinsatzNummer(presence.getMsg());
        }

        public void presenceRemoved(LLPresence presence) {
            removeEinsatzNummer(presence.getMsg());
        }

    }
}
